# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# - name: Cleanup Homebrew cask
#   ansible.builtin.command: "brew cleanup"
#   tags: cache

# - name: Appstore | Upgrade all installed Mac App Store apps
#   community.general.mas:
#     upgrade_all: true
