# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Include OS-specific tasks
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Finish | Core
      ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: Include Unix specific tasks
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Finish | Unix configuration
      ansible.builtin.include_tasks: "unix.yml"
