# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Directory | Change applications directory rights
  ansible.builtin.file:
    path: /Users/{{ user }}/Applications
    state: directory
    owner: "{{ user }}"
    # group: "{{ user }}"
    mode: 0755

- name: Directory | Change user binaries directory rights
  ansible.builtin.file:
    path: /Users/{{ user }}/bin
    state: directory
    owner: "{{ user }}"
    # group: "{{ user }}"
    mode: 0755
