# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# defaults file for cloud
homebrew_taps_cloud:
  - hashicorp/tap
  - kwilczynski/homebrew-pkenv
  - kubescape/tap
  - chainguard-dev/tap
  - keidarcy/tap
