# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: HomeBrew | Common editors (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - visual-studio-code
      # - emacs
      - zed

- name: HomeBrew | Common editors
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - neovim
