# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: HomeBrew | Install Virtualbox
  community.general.homebrew_cask:
    name: virtualbox
    state: present
    accept_external_apps: true

- name: HomeBrew | Install Vagrant
  community.general.homebrew_cask:
    name: vagrant
    state: present
    accept_external_apps: true

- name: HomeBrew | Install Docker tools
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
    accept_external_apps: true
  vars:
    packages:
      - dockertoolbox

# - name: HomeBrew | Install QEmu
#   community.general.homebrew:
#     name: qemu
#     state: present
#     accept_external_apps: true
