# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Appstore | Sign in
  ansible.builtin.pause:
    prompt: Press Ctrl+C to quit now if you have not already signed in to App Store
    seconds: "{{ appstore_pause }}"

- name: Appstore | Installs mas-cli with Homebrew
  community.general.homebrew:
    name: "{{ appstore_mas_package }}"

- name: Appstore | Install applications
  ansible.builtin.command: "mas install {{ item }}"
  register: result
  changed_when: result.stdout.find('Installed') != 1
  loop: "{{ appstore_applications }}"

- name: Appstore | Update applications
  ansible.builtin.command: "mas upgrade {{ item }}"
  register: result
  changed_when: result.stdout.find('Installed') != 1
  loop: "{{ appstore_applications }}"
