# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# - name: Install | Finder tools
#   community.general.homebrew_cask:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - zoxide

- name: Install | Finder tools (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openinterminal
      - ueli
      - maccy
      - marta

- name: Install | Web applications
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - google-chrome
      # - brave
      - firefox

- name: Install | Graphics applications
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - graphviz

- name: Install | Graphics applications (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - flameshot
      - monitorcontrol

- name: Install | Video applications
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Install | Music applications
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - spotify

- name: Install | Communications applications
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - slack
      - meetingbar
      - noti

- name: Install | Security tools (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - 1password
      - 1password-cli
      - bitwarden
      - wireshark
      - tailscale
      - gpg-suite
      - keka
      - opkssh

- name: Install | Security tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - pinentry-mac
      - age
      - age-plugin-yubikey
      - rustscan
      - ykman
      - gitsign

- name: Packages | Networking tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - grpcurl
      - hurl

- name: Install | Networking tools (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lulu
      - sloth
      - transmission

- name: Install | System tools (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sol
      - balenaetcher

- name: Install | System tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - zenith
      - xplr
      - yazi
      - sk

- name: Install | AI tools (Cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - brew install --cask amazon-q
