# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# handlers file for base

- name: Clear homebrew cache
  ansible.builtin.file:
    path: "{{ homebrew_cache_path.stdout | trim }}"
    state: absent
  when: 'homebrew_clear_cache | bool'
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: Killall dock
  ansible.builtin.command: killall Dock
  become: true
  failed_when: false

- name: Killall finder
  ansible.builtin.command: killall Finder
  become: true
  failed_when: false

- name: Killall systemuiserver
  ansible.builtin.command: killall SystemUIServer
  become: true
  failed_when: false
