# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
homebrew_taps_desktop:
  - koekeishiya/formulae
  - sigstore/tap
  - openpubkey/opkssh

appstore_applications: []
