# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: System | Ensure configured taps are tapped.
  community.general.homebrew_tap:
    name: '{{ item.name | default(item) }}'
    url: '{{ item.url | default(omit) }}'
    state: present
  loop: "{{ homebrew_taps_desktop }}"

- name: Install | Windows manager
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - yabai
      - skhd
      # - amethyst
      # - rectangle

- name: Install | Windows manager addons
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sketchybar

- name: Install | Windows manager addons (cask)
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - font-hack-nerd-font

# - name: System | Restart yabai
#   ansible.builtin.command: brew services restart yabai

# - name: System | Restart skhd
#   ansible.builtin.command: brew services restart skhd
