# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Install management tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mas
      - mise
      # - asdf

- name: Packages | Install terminal emulators
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - iterm2
      # - alacritty
      # - wezterm
      - ghostty

- name: Packages | Install core tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fzf
      - tmux
      - ncdu
      - git
      - gpg2
      - pinentry
      - wget
      - gitui
      - starship
      - direnv
      - yq
      - jq

- name: Packages | Install modern Unix tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - zellij
      - bat
      - ripgrep
      - eza
      - fd

- name: Packages | Install precommit tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - shellcheck
      - shfmt
