# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: LSP | Install tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bash-language-server
      - ansible-language-server
      - gopls
      - rust-analyzer
      - terraform-ls
