# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Include OS-specific tasks
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Base | Homebrew
      ansible.builtin.include_tasks: "homebrew.yml"
    - name: Base | Applications
      ansible.builtin.include_tasks: "apps.yml"
    - name: Base | Unix
      ansible.builtin.include_tasks: "unix.yml"
    - name: Base | Languages
      ansible.builtin.include_tasks: "lang.yml"
    - name: Base | Defaults
      ansible.builtin.include_tasks: "defaults.yml"
