# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# TODO: Does not work on Github Action MacOS runner
# - name: System | Ensure user exists
#   ansible.builtin.user:
#     name: "{{ user }}"
#     shell: /bin/zsh
#     groups: admin
#     append: true

- name: User | Create binary directory
  ansible.builtin.file:
    path: /Users/{{ user }}/bin
    owner: "{{ user }}"
    # group: "{{ user }}"
    state: directory
    mode: 0755

- name: User | Create configuration directory
  ansible.builtin.file:
    path: /Users/{{ user }}/etc
    owner: "{{ user }}"
    # group: "{{ user }}"
    state: directory
    mode: 0755

- name: User | Create XDG directories
  ansible.builtin.file:
    path: /Users/{{ user }}/{{ item }}
    owner: "{{ user }}"
    # group: "{{ user }}"
    state: directory
    mode: 0755
  loop: "{{ xdg_dirs }}"

- name: User | Create user directories
  ansible.builtin.file:
    path: /Users/{{ user }}/{{ item }}
    owner: "{{ user }}"
    # group: "{{ user }}"
    state: directory
    mode: 0755
  loop: "{{ user_dirs }}"
